/**
 * Sub clean_up
 * return {void}
 */
function clean_up () {
	//custom classes;
	gContTableCombined = undefined;
	gContTableMed = undefined;
	gContTableRx = undefined;
	gDEDROW = undefined;
	gDEDROW_MED = undefined;
	gDEDROW_RX = undefined;
	//marginal distributions;
	gUpToCol = undefined;
	gMaxdCol = undefined;
	gER = undefined;
	gIP = undefined;
	gPC = undefined;
	gPCN = undefined;
	gSP = undefined;
	gPSY = undefined;
	gIMG = undefined;
	gST = undefined;
	gOT = undefined;
	gPREV = undefined;
	gLAB = undefined;
	gSNF = undefined;
	gUNCL = undefined;
	gXRAY = undefined;
	gXRAY_PC = undefined;
	gXRAY_SP = undefined;
	gXRAY_UNC = undefined;
	gOPFAC_PSY = undefined;
	gOPFAC_IMG = undefined;
	gOPFAC_ST = undefined;
	gOPFAC_OT = undefined;
	gOPFAC_LAB = undefined;
	gOPFAC_UNC = undefined;
	gOPPROF_PSY = undefined;
	gOPPROF_IMG = undefined;
	gOPPROF_ST = undefined;
	gOPPROF_OT = undefined;
	gOPPROF_LAB = undefined;
	gOPPROF_SRGRY = undefined;
	gRXGEN = undefined;
	gRXFORM = undefined;
	gRXNONFORM = undefined;
	gRXSPCLTY = undefined;
	gUpToCol_MEDTBL = undefined;
	gMaxdCol_MEDTBL = undefined;
	gER_MEDTBL = undefined;
	gIP_MEDTBL = undefined;
	gPC_MEDTBL = undefined;
	gPCN_MEDTBL = undefined;
	gSP_MEDTBL = undefined;
	gPSY_MEDTBL = undefined;
	gIMG_MEDTBL = undefined;
	gST_MEDTBL = undefined;
	gOT_MEDTBL = undefined;
	gPREV_MEDTBL = undefined;
	gLAB_MEDTBL = undefined;
	gSNF_MEDTBL = undefined;
	gUNCL_MEDTBL = undefined;
	gXRAY_MEDTBL = undefined;
	gXRAY_PC_MEDTBL = undefined;
	gXRAY_SP_MEDTBL = undefined;
	gXRAY_UNC_MEDTBL = undefined;
	gOPFAC_PSY_MEDTBL = undefined;
	gOPFAC_IMG_MEDTBL = undefined;
	gOPFAC_ST_MEDTBL = undefined;
	gOPFAC_OT_MEDTBL = undefined;
	gOPFAC_LAB_MEDTBL = undefined;
	gOPFAC_UNC_MEDTBL = undefined;
	gOPPROF_PSY_MEDTBL = undefined;
	gOPPROF_IMG_MEDTBL = undefined;
	gOPPROF_ST_MEDTBL = undefined;
	gOPPROF_OT_MEDTBL = undefined;
	gOPPROF_LAB_MEDTBL = undefined;
	gOPPROF_SRGRY_MEDTBL = undefined;
	gUpToCol_RXTBL = undefined;
	gMaxdCol_RXTBL = undefined;
	gRXGEN_RXTBL = undefined;
	gRXFORM_RXTBL = undefined;
	gRXNONFORM_RXTBL = undefined;
	gRXSPCLTY_RXTBL = undefined;
	//arrays;
	delete gCombinedLabels_Arr;
	delete gMedicalLabels_Arr;
	delete gRxLabels_Arr;
	delete gMedical_Arr;
	delete gRx_Arr;
	delete gMedSvcCopayNR_Arr;
	delete gMedSvcCoinsNR_Arr;
	delete gRxSvcCopayNR_Arr;
	delete gRxSvcCoinsNR_Arr;
	delete gSTDED_ARR;
	delete gSTCOINS_ARR;
	delete gOMIT_ARR;
	delete gSTDEDRX_ARR;
	delete gSTCOINSRX_ARR;
	delete gOMITRX_ARR;
	//other;
	gSTATUS_MSG = "";
	gNOTE_MSG = "";
	gERROR_FLAG = 0;
	gOPFAC_PSY_OVRD = 0;
	gOPFAC_IMG_OVRD = 0;
	gOPFAC_ST_OVRD = 0;
	gOPFAC_OT_OVRD = 0;
	gOPFAC_LAB_OVRD = 0;
	gOPPROF_PSY_OVRD = 0;
	gOPPROF_IMG_OVRD = 0;
	gOPPROF_ST_OVRD = 0;
	gOPPROF_OT_OVRD = 0;
	gOPPROF_LAB_OVRD = 0;
	gNOTE_XRAY_OVRD = 0;
	gNOTE_OP_OVRD = 0;
	gAV = 0;
	gBENEPAY_COINSRNG = 0;
	gNESTED_DEDUCT_IND = 0;
	gPLAN_PAY = 0;
	gPLAN_PAY_COINSRNG = 0;
	gTOT_PAY = 0;
	gTOT_PAY_MED = 0;
	gTOT_PAY_RX = 0;
	gBENEPAY_DEDUCT_MED = 0;
	gBENEPAY_DEDUCT_RX = 0;
	gBENECOINS_DEDUCT = 0;
	gDEDUCT_ADJMT = 0;
	gMOOP_ADJMT = 0;
	gMOOP_ADJMT_MED = 0;
	gMOOP_ADJMT_RX = 0;
	gADJ_DEDUCT = 0;
	gADJ_DEDUCT_MED = 0;
	gADJ_DEDUCT_RX = 0;
	gADJ_MOOP = 0;
	gADJ_MOOP_MED = 0;
	gADJ_MOOP_RX = 0;
	gTROOP = 0;
	gTROOP_MED = 0;
	gTROOP_RX = 0;
	gEFF_COINS = 0;
	gEFF_COINS_MED = 0;
	gEFF_COINS_RX = 0;
	gEFF_COINS_NUM = 0;
	gEFF_COINS_NUM_MED = 0;
	gEFF_COINS_NUM_RX = 0;
	gEFF_COINS_DENOM_MED = 0;
	gEFF_COINS_DENOM_RX = 0;
	gAV_DENOM = 0;
}
